categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"

  - title: ":rocket: Features"
    label: "enhancement"

  - title: ":fire: Removals and Deprecations"
    label: "removal"

  - title: ":bug: Fixes"
    label: "bug"

  - title: ":racehorse: Performance"
    label: "performance"

  - title: ":rotating_light: Testing"
    label: "testing"

  - title: ":construction_worker: Continuous Integration"
    label: "ci"

  - title: ":books: Documentation"
    label: "documentation"

  - title: ":hammer: Refactoring"
    label: "refactoring"

  - title: ":lipstick: Style"
    label: "style"

  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"

category-template: "### $TITLE"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

exclude-contributors:
  - "robbievanleeuwen"

# Custom text at start of release
header: >

  This release contains several important bug fixes and dependency updates.

  Python 3.9 support is dropped ahead of the upcoming 3.13 release. Python 3.13 support
  will be added once all the core upstream dependencies support 3.13.

  A bug in the `CompoundGeometry` offset dilation algorithm was fixed by @connorferster,
  a live stream of this fix can be watched [here](https://www.youtube.com/live/hSfsojAAJjc?si=Zuwn7Mr6zXS1wHFF).

  Most importantly a critical bug in the plastic moment calculation was found and fixed,
  see issue 460. Note that this bug affected plastic moment calculations for composite
  sections only, the plastic centroid calculation and geometric-only analyses were
  unaffected.

template: |

  ## What's Changed

  $CHANGES

footer: |

  **Full changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/robbievanleeuwen/section-properties/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
